name: Build Example Pipeline

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show simple message
        shell: bash
        run: echo "Hello World!"  
      
      - name: Show simple message in another repository
        uses: rafaelgoncalvesmatos/DevOpsPipelineTemplates/.github/workflows/infra-deploy.yml