name: Build Example Pipeline

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: rafaelgoncalvesmatos/DevopsPipelineTemplate/.github/workflows/infra-deploy.yml@devops
      