name: HelloWorld 

on:
  workflow_dispatch:
  push:
    branches:
      - devops

jobs:
  checkout:
    uses: rafaelgoncalvesmatos/DevOpsPipelineTemplates/.github/workflows/infra-deploy.yml@devops
    with:
      jdk_version: 11